### ISSUE TITLE
Deprecated API used in a-basic

### ISSUE THREAD

**Issue by greenlaw110** [ebean-orm/avaje-ebeanorm-examples#3]
The following code:

```java
@Entity
@Table(name="be_contact")
public class Contact extends BaseModel {

  /**
   * Convenience Finder for 'active record' style.
   */
  public static final Finder<Long,Contact> find = new Finder<>(Long.class, Contact.class);
...
```

is using deprecated API:

```java
        /** @deprecated */
        public Finder(Class<I> idType, Class<T> type) {
            super((String)null, type);
        }
```

**Comment by rbygrave** [comment]
Fix now.  Thanks.

**Comment by greenlaw110** [comment]
Actually I was wondering what if user are using Long as the ID type as Finder now only accept String type ID?

**Comment by rbygrave** [comment]
Right.

The reason is because the actual type of the ID (Long.class, String.class,
UUID.class etc) is not actually needed to pass to the EbeanServer.  It is
sufficient that it is simply the generic type on the Finder.

On the other hand, the "bean type" Customer.class etc is actually needed to
build the appropriate Query<Customer>.

Does that make sense?
